# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit mcinerney-burke.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.align = "center"
)


## ----software-comparison-table, echo = FALSE, results = "asis"----------------
software_comparison <- data.frame(
  Package = c("statnnet", "pdp", "NeuralNetTools", "NeuralSens", "cito"),
  `Fit or interface` = c(
    "Existing `nnet` fit.",
    "Many model classes.",
    "`nnet` and other NNs.",
    "`nnet` and other MLPs.",
    "Own `torch` fits."
  ),
  `Primary output` = c(
    "Row/PD effects; analytic grouped Wald.",
    "PD and ICE curves.",
    "Plots, weight importance, Lek profiles.",
    "Input-derivative sensitivities.",
    "ACE, PDP/ALE, importance; bootstrap."
  ),
  check.names = FALSE
)

knitr::kable(
  software_comparison,
  caption = "Closest R packages for neural-network interpretation and effect summaries.",
  escape = FALSE
)


## ----software-side-by-side, echo = TRUE, eval = FALSE-------------------------
# # statnnet: scalar observed-row effect and scalar PD contrast
# rowwise_effects <- summary(snn, effects = "rowwise")$pce
# partial_bmi <- pce(
#   snn, variable = "bmi", type = "average", uncertainty = "none"
# )
# 
# # pdp: the PD response curve rather than its finite difference
# pdp_bmi <- pdp::partial(
#   nn, pred.var = "bmi", train = insurance_analysis, plot = FALSE
# )
# 
# # NeuralNetTools: connection-weight importance
# weight_importance <- NeuralNetTools::olden(nn)
# 
# # NeuralSens: derivatives of the fitted response with respect to inputs
# input_sensitivity <- NeuralSens::SensAnalysisMLP(
#   nn, trData = insurance_analysis, plot = FALSE
# )


## ----nnet-comparison-table, echo = FALSE, results = "asis"--------------------
nnet_comparison <- data.frame(
  Task = c(
    "Model fitting",
    "Default summary",
    "Parameter covariance",
    "Covariate-level assessment",
    "Covariate-effect description",
    "Numerical diagnostics",
    "Prediction"
  ),
  `nnet` = c(
    "Fits by BFGS.",
    "Architecture and connection weights.",
    "Not generally supplied.",
    "Not provided.",
    "Not provided.",
    "Convergence; optional Hessian.",
    "Provided by `predict.nnet()`."
  ),
  `statnnet` = c(
    "Retains the fit; no refitting.",
    "Effects and grouped Wald summaries.",
    "Penalised sandwich estimate.",
    "Grouped Wald summaries.",
    "Rowwise effects and PD plots.",
    "Adds covariance checks.",
    "Delegates to the retained fit."
  ),
  check.names = FALSE
)

knitr::kable(
  nnet_comparison,
  caption = "Information available from a native \\CRANpkg{nnet} fit and after augmentation by \\pkg{statnnet}.",
  escape = FALSE
)


## ----statnnet-call, echo = TRUE, eval = FALSE---------------------------------
# statnnet(object, formula, data, ...)


## ----example-data, echo = TRUE------------------------------------------------
library(statnnet)
library(nnet)

data("insurance", package = "statnnet")

names(insurance)
head(insurance[, c("age", "sexmale", "bmi", "children", "smokeryes", "charges")])


## ----example-region-factor, echo = FALSE--------------------------------------
insurance_analysis <- insurance
insurance_analysis$region <- factor(
  ifelse(
    insurance$regionnorthwest == 1,
    "northwest",
    ifelse(
      insurance$regionsoutheast == 1,
      "southeast",
      ifelse(insurance$regionsouthwest == 1, "southwest", "northeast")
    )
  ),
  levels = c("northeast", "northwest", "southeast", "southwest")
)
insurance_analysis[c(
  "regionnorthwest", "regionsoutheast", "regionsouthwest"
)] <- NULL


## ----example-formula, echo = TRUE---------------------------------------------
insurance_formula <- charges ~ .


## ----example-fit, echo = TRUE-------------------------------------------------
set.seed(1237019)

nnet_fits <- replicate(
  10,
  nnet(
    insurance_formula,
    data = insurance_analysis,
    size = 2,
    linout = TRUE,
    decay = 0.01,
    maxit = 1000,
    Hess = TRUE,
    trace = FALSE
  ),
  simplify = FALSE
)

converged <- vapply(nnet_fits, function(fit) fit$convergence == 0, logical(1))
stopifnot(any(converged))

objective <- vapply(nnet_fits, function(fit) fit$value, numeric(1))
objective[!converged] <- Inf
nn <- nnet_fits[[which.min(objective)]]


## ----example-native-summary, echo = TRUE, results = "hide"--------------------
summary(nn)


## ----example-create-statnnet, echo = TRUE-------------------------------------
snn <- statnnet(
  object = nn,
  formula = insurance_formula,
  data = insurance_analysis,
  response = "continuous"
)


## ----example-print, echo = TRUE-----------------------------------------------
print(snn)


## ----example-summary, echo = TRUE---------------------------------------------
snn_summary <- summary(snn)
snn_summary$pce


## ----example-summary-partial, echo = TRUE, eval = FALSE-----------------------
# summary(snn, effects = "partial")


## ----example-summary-single, echo = TRUE, results = "hide"--------------------
summary(snn, weights = TRUE)


## ----example-anova, echo = TRUE-----------------------------------------------
anova(snn)


## ----example-plotnn, echo = TRUE, fig.width = 6.5, fig.height = 4.2, out.width = "72%", fig.cap = "Fitted neural-network architecture for the insurance data. The diagram shows the input nodes, hidden nodes, output node, and fitted connections; annotations are suppressed here to keep the dense diagram legible.", fig.alt = "A neural-network architecture diagram with eight input nodes, two hidden nodes, one output node, and directed connections between layers."----
plotnn(snn, annotate = "none")


## ----example-plotnn-alpha, echo = TRUE, fig.show = "hide"---------------------
plotnn(snn, annotate = "p_value", alpha = 0.01)


## ----example-pce-bmi, echo = TRUE, fig.width = 6.5, fig.height = 4, out.width = "72%", fig.cap = "Partial covariate-effect plot for body mass index in the insurance data. The plot shows the estimated change in fitted charges associated with a change in standardised body mass index over the observed covariate range.", fig.alt = "A partial covariate-effect plot for body mass index, with body mass index on the horizontal axis and the estimated covariate effect on the vertical axis."----
plot(snn, variable = "bmi", uncertainty = "none")


## ----pdp-agreement-table, echo = FALSE, results = "asis"----------------------
comparison_value <- 0
comparison_step <- sd(insurance_analysis$bmi)

statnnet_bmi <- pce(
  snn,
  variable = "bmi",
  values = comparison_value,
  d = comparison_step,
  uncertainty = "none"
)

pdp_bmi <- pdp::partial(
  nn,
  pred.var = "bmi",
  pred.grid = data.frame(
    bmi = c(comparison_value, comparison_value + comparison_step)
  ),
  train = insurance_analysis,
  plot = FALSE
)

pdp_difference <- diff(pdp_bmi$yhat)
pdp_agreement <- data.frame(
  Method = c("statnnet PCE", "finite difference of pdp PD"),
  Estimate = c(statnnet_bmi$estimate, pdp_difference)
)
pdp_agreement$`Absolute difference from statnnet` <-
  abs(pdp_agreement$Estimate - statnnet_bmi$estimate)

knitr::kable(
  pdp_agreement,
  digits = 8
)


## ----example-pce-smoker, echo = TRUE, fig.show = "hide"-----------------------
plot(snn, variable = "smokeryes", uncertainty = "none")


## ----example-pce-multiple, echo = TRUE, fig.show = "hide"---------------------
plot(
  snn,
  variable = c("age", "bmi", "children", "smokeryes"),
  uncertainty = "none"
)


## ----example-pce-delta, echo = TRUE, fig.width = 6.5, fig.height = 4, out.width = "72%"----
plot(
  snn,
  variable = "age",
  uncertainty = "delta"
)


## ----example-pce-sim, echo = TRUE, eval = FALSE-------------------------------
# plot(
#   snn,
#   variable = "age",
#   uncertainty = "simulation"
# )


## ----example-pce-interaction, echo = TRUE, fig.width = 6.5, fig.height = 4, out.width = "72%"----
plot(
  snn,
  variable = "bmi",
  by = "smokeryes",
  uncertainty = "delta"
)


## ----example-predict-training, echo = TRUE------------------------------------
fitted_values <- predict(snn)

head(fitted_values)


## ----example-predict-newdata, echo = TRUE-------------------------------------
new_insurance <- insurance_analysis[
  1:5,
  setdiff(names(insurance_analysis), "charges")
]

predict(snn, newdata = new_insurance)


## ----statnnet-methods-table, echo = FALSE, results = "asis"-------------------
knitr::kable(
  data.frame(
    Function = c(
      "`statnnet()`",
      "`print()`",
      "`summary()`",
      "`anova()`",
      "`vcov()`",
      "`plot()`",
      "`plotnn()`",
      "`predict()`"
    ),
    Purpose = c(
      "Validates and augments an `nnet` fit.",
      "Prints architecture and diagnostics.",
      "Reports effects and grouped Wald summaries.",
      "Reports grouped Wald summaries.",
      "Returns the covariance estimate.",
      "Plots PCEs and pointwise intervals.",
      "Draws an annotated network.",
      "Delegates prediction to the retained fit."
    )
  ),
  caption = "Main user-facing functions and methods in statnnet.",
  escape = TRUE
)

