# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit new-draft.Rmd to modify this file

## ----setup, include=FALSE--------------------------------------------------------
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.align = "center"
)


## ----nnet-comparison-table, echo = FALSE, results = "asis"-----------------------
nnet_comparison <- data.frame(
  Task = c(
    "Model fitting",
    "Default summary",
    "Parameter covariance",
    "Covariate-level assessment",
    "Covariate-effect description",
    "Numerical diagnostics",
    "Prediction"
  ),
  `Native nnet object` = c(
    "Fits the network by BFGS.",
    "Architecture, options, and connection weights.",
    "Not available for a general nnet fit.",
    "Not provided.",
    "Not provided.",
    "Convergence code and optional Hessian.",
    "Provided by predict.nnet()."
  ),
  `statnnet augmentation` = c(
    "Does not refit the model.",
    "PCEs, standard errors, and grouped Wald-type summaries.",
    "Penalty-adjusted sandwich estimate.",
    "Grouped Wald-type summaries, including factors.",
    "PCE summaries and plots with uncertainty intervals.",
    "Convergence and covariance checks.",
    "Delegates to the retained nnet fit."
  ),
  check.names = FALSE
)

knitr::kable(
  nnet_comparison,
  caption = "Information available from a native \\CRANpkg{nnet} fit and after augmentation by \\pkg{statnnet}.",
  escape = FALSE
)


## ----statnnet-call, echo = TRUE, eval = FALSE------------------------------------
# statnnet(object, formula, data, ...)


## ----example-data, echo = TRUE---------------------------------------------------
library(statnnet)
library(nnet)

data("insurance", package = "statnnet")

names(insurance)
head(insurance[, c("age", "sexmale", "bmi", "children", "smokeryes", "charges")])


## ----example-formula, echo = TRUE------------------------------------------------
insurance_formula <- charges ~ .


## ----example-fit, echo = TRUE----------------------------------------------------
set.seed(1237019)

nnet_fits <- replicate(
  10,
  nnet(
    insurance_formula,
    data = insurance,
    size = 2,
    linout = TRUE,
    decay = 0.01,
    maxit = 1000,
    Hess = TRUE,
    trace = FALSE
  ),
  simplify = FALSE
)

converged <- vapply(nnet_fits, function(fit) fit$convergence == 0, logical(1))
stopifnot(any(converged))

objective <- vapply(nnet_fits, function(fit) fit$value, numeric(1))
objective[!converged] <- Inf
nn <- nnet_fits[[which.min(objective)]]


## ----example-native-summary, echo = TRUE-----------------------------------------
summary(nn)


## ----example-create-statnnet, echo = TRUE----------------------------------------
snn <- statnnet(
  object = nn,
  formula = insurance_formula,
  data = insurance,
  response = "continuous"
)


## ----example-print, echo = TRUE--------------------------------------------------
print(snn)


## ----example-summary, echo = TRUE------------------------------------------------
summary(snn)


## ----example-summary-single, echo = TRUE-----------------------------------------
summary(snn, weights = TRUE)


## ----example-anova, echo = TRUE--------------------------------------------------
anova(snn)


## ----example-plotnn, echo = TRUE, fig.cap = "Fitted neural-network architecture for the insurance data. The diagram shows the input nodes, hidden nodes, output node, and fitted connections, with the default annotation used by `plotnn()`.", fig.alt = "A neural-network architecture diagram with eight input nodes, two hidden nodes, one output node, and directed connections between layers."----
plotnn(snn)


## ----example-plotnn-alpha, echo = TRUE-------------------------------------------
plotnn(snn, alpha = 0.01)


## ----example-plotnn-intercept, echo = TRUE---------------------------------------
plotnn(snn, intercept = TRUE)


## ----example-pce-bmi, echo = TRUE, fig.cap = "Partial covariate-effect plot for body mass index in the insurance data. The plot shows the estimated change in fitted charges associated with a change in standardised body mass index over the observed covariate range.", fig.alt = "A partial covariate-effect plot for body mass index, with body mass index on the horizontal axis and the estimated covariate effect on the vertical axis."----
plot(snn, variable = "bmi", uncertainty = "none")


## ----example-pce-smoker, echo = TRUE, fig.cap = "Partial covariate-effect plot for smoking status in the insurance data. The plot shows the estimated change in fitted charges associated with the smoking-status dummy variable.", fig.alt = "A partial covariate-effect plot for smoking status, with the smoking-status dummy variable on the horizontal axis and the estimated covariate effect on the vertical axis."----
plot(snn, variable = "smokeryes", uncertainty = "none")


## ----example-pce-multiple, echo = TRUE, fig.cap = "Partial covariate-effect plots for selected covariates in the insurance data. The panels show estimated covariate effects for age, body mass index, number of children, and smoking status.", fig.alt = "A set of partial covariate-effect plots for age, body mass index, children, and smoking status."----
plot(
  snn,
  variable = c("age", "bmi", "children", "smokeryes"),
  uncertainty = "none"
)


## ----example-pce-delta, echo = TRUE----------------------------------------------
plot(
  snn,
  variable = "age",
  uncertainty = "delta"
)


## ----example-pce-sim, echo = TRUE------------------------------------------------
plot(
  snn,
  variable = "age",
  uncertainty = "simulation"
)


## ----example-pce-interaction, echo = TRUE----------------------------------------
plot(
  snn,
  variable = "age",
  by = "smokeryes",
  uncertainty = "delta"
)


## ----example-predict-training, echo = TRUE---------------------------------------
fitted_values <- predict(snn)

head(fitted_values)


## ----example-predict-newdata, echo = TRUE----------------------------------------
new_insurance <- insurance[1:5, setdiff(names(insurance), "charges")]

predict(snn, newdata = new_insurance)


## ----statnnet-methods-table, echo = FALSE, results = "asis"----------------------
knitr::kable(
  data.frame(
    Function = c(
      "`statnnet()`",
      "`print()`",
      "`summary()`",
      "`anova()`",
      "`vcov()`",
      "`plot()`",
      "`plotnn()`",
      "`predict()`"
    ),
    Purpose = c(
      "Validates and augments a supported object of class `nnet`.",
      "Prints a compact description of the fitted network and its diagnostics.",
      "Produces regression-style summaries, including PCE estimates and Wald-type summaries.",
      "Produces covariate-level Wald-type summaries, including grouped summaries for categorical covariates.",
      "Returns the estimated covariance matrix when its diagnostic checks are satisfied.",
      "Produces partial covariate-effect plots, with optional uncertainty intervals.",
      "Produces a neural-network architecture diagram annotated with Wald-type summaries.",
      "Returns fitted values or predictions for new observations."
    )
  ),
  caption = "Main user-facing functions and methods in statnnet.",
  escape = TRUE
)

