# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit new-draft.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.align = "center"
)


## ----nnet-comparison-table, echo = FALSE, results = "asis"--------------------
nnet_comparison <- data.frame(
  Task = c(
    "Model fitting",
    "Default summary",
    "Parameter covariance",
    "Covariate-level assessment",
    "Covariate-effect description",
    "Numerical diagnostics",
    "Prediction"
  ),
  `nnet` = c(
    "Fits by BFGS.",
    "Architecture and connection weights.",
    "Not generally supplied.",
    "Not provided.",
    "Not provided.",
    "Convergence; optional Hessian.",
    "Provided by `predict.nnet()`."
  ),
  `statnnet` = c(
    "Retains the fit; no refitting.",
    "Effects and grouped Wald summaries.",
    "Penalised sandwich estimate.",
    "Grouped Wald summaries.",
    "PCE summaries and plots.",
    "Adds covariance checks.",
    "Delegates to the retained fit."
  ),
  check.names = FALSE
)

knitr::kable(
  nnet_comparison,
  caption = "Information available from a native \\CRANpkg{nnet} fit and after augmentation by \\pkg{statnnet}.",
  escape = FALSE
)


## ----statnnet-call, echo = TRUE, eval = FALSE---------------------------------
# statnnet(object, formula, data, ...)


## ----example-data, echo = TRUE------------------------------------------------
library(statnnet)
library(nnet)

data("insurance", package = "statnnet")

names(insurance)
head(insurance[, c("age", "sexmale", "bmi", "children", "smokeryes", "charges")])


## ----example-region-factor, echo = TRUE---------------------------------------
insurance_analysis <- insurance
insurance_analysis$region <- factor(
  ifelse(
    insurance$regionnorthwest == 1,
    "northwest",
    ifelse(
      insurance$regionsoutheast == 1,
      "southeast",
      ifelse(insurance$regionsouthwest == 1, "southwest", "northeast")
    )
  ),
  levels = c("northeast", "northwest", "southeast", "southwest")
)
insurance_analysis[c(
  "regionnorthwest", "regionsoutheast", "regionsouthwest"
)] <- NULL


## ----example-formula, echo = TRUE---------------------------------------------
insurance_formula <- charges ~ .


## ----example-fit, echo = TRUE-------------------------------------------------
set.seed(1237019)

nnet_fits <- replicate(
  10,
  nnet(
    insurance_formula,
    data = insurance_analysis,
    size = 2,
    linout = TRUE,
    decay = 0.01,
    maxit = 1000,
    Hess = TRUE,
    trace = FALSE
  ),
  simplify = FALSE
)

converged <- vapply(nnet_fits, function(fit) fit$convergence == 0, logical(1))
stopifnot(any(converged))

objective <- vapply(nnet_fits, function(fit) fit$value, numeric(1))
objective[!converged] <- Inf
nn <- nnet_fits[[which.min(objective)]]


## ----example-native-summary, echo = TRUE--------------------------------------
summary(nn)


## ----example-create-statnnet, echo = TRUE-------------------------------------
snn <- statnnet(
  object = nn,
  formula = insurance_formula,
  data = insurance_analysis,
  response = "continuous"
)


## ----example-print, echo = TRUE-----------------------------------------------
print(snn)


## ----example-summary, echo = TRUE---------------------------------------------
summary(snn)


## ----example-summary-partial, echo = TRUE, eval = FALSE-----------------------
# summary(snn, effects = "partial")


## ----example-summary-single, echo = TRUE, results = "hide"--------------------
summary(snn, weights = TRUE)


## ----example-anova, echo = TRUE-----------------------------------------------
anova(snn)


## ----example-plotnn, echo = TRUE, fig.cap = "Fitted neural-network architecture for the insurance data. The diagram shows the input nodes, hidden nodes, output node, and fitted connections; annotations are suppressed here to keep the dense diagram legible.", fig.alt = "A neural-network architecture diagram with eight input nodes, two hidden nodes, one output node, and directed connections between layers."----
plotnn(snn, annotate = "none")


## ----example-plotnn-alpha, echo = TRUE, fig.show = "hide"---------------------
plotnn(snn, annotate = "p_value", alpha = 0.01)


## ----example-pce-bmi, echo = TRUE, fig.cap = "Partial covariate-effect plot for body mass index in the insurance data. The plot shows the estimated change in fitted charges associated with a change in standardised body mass index over the observed covariate range.", fig.alt = "A partial covariate-effect plot for body mass index, with body mass index on the horizontal axis and the estimated covariate effect on the vertical axis."----
plot(snn, variable = "bmi", uncertainty = "none")


## ----example-pce-smoker, echo = TRUE, fig.show = "hide"-----------------------
plot(snn, variable = "smokeryes", uncertainty = "none")


## ----example-pce-multiple, echo = TRUE, fig.show = "hide"---------------------
plot(
  snn,
  variable = c("age", "bmi", "children", "smokeryes"),
  uncertainty = "none"
)


## ----example-pce-delta, echo = TRUE-------------------------------------------
plot(
  snn,
  variable = "age",
  uncertainty = "delta"
)


## ----example-pce-sim, echo = TRUE, fig.show = "hide"--------------------------
plot(
  snn,
  variable = "age",
  uncertainty = "simulation"
)


## ----example-pce-interaction, echo = TRUE-------------------------------------
plot(
  snn,
  variable = "bmi",
  by = "smokeryes",
  uncertainty = "delta"
)


## ----example-predict-training, echo = TRUE------------------------------------
fitted_values <- predict(snn)

head(fitted_values)


## ----example-predict-newdata, echo = TRUE-------------------------------------
new_insurance <- insurance_analysis[
  1:5,
  setdiff(names(insurance_analysis), "charges")
]

predict(snn, newdata = new_insurance)


## ----statnnet-methods-table, echo = FALSE, results = "asis"-------------------
knitr::kable(
  data.frame(
    Function = c(
      "`statnnet()`",
      "`print()`",
      "`summary()`",
      "`anova()`",
      "`vcov()`",
      "`plot()`",
      "`plotnn()`",
      "`predict()`"
    ),
    Purpose = c(
      "Validates and augments an `nnet` fit.",
      "Prints architecture and diagnostics.",
      "Reports effects and grouped Wald summaries.",
      "Reports grouped Wald summaries.",
      "Returns the covariance estimate.",
      "Plots PCEs and pointwise intervals.",
      "Draws an annotated network.",
      "Delegates prediction to the retained fit."
    )
  ),
  caption = "Main user-facing functions and methods in statnnet.",
  escape = TRUE
)

