# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit test.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(plotly)
library(ggplot2)
library(palmerpenguins)
library(kableExtra)


## ----software-comparison-table, echo = FALSE, results = "asis"----------------
software_comparison <- data.frame(
  Package = c(
    "\\CRANpkg{nnet}",
    "\\CRANpkg{neuralnet}",
    "\\CRANpkg{keras}",
    "\\CRANpkg{torch}",
    "\\CRANpkg{pdp}",
    "\\CRANpkg{iml}",
    "\\CRANpkg{DALEX}",
    "\\CRANpkg{vip}",
    "\\pkg{interpretnn}"
  ),
  `Main role` = c(
    "Fitting shallow neural networks.",
    "Fitting shallow neural networks.",
    "Deep-learning interface.",
    "Deep-learning framework.",
    "Partial dependence and related plots.",
    "Model-agnostic interpretability.",
    "Model-agnostic explainability.",
    "Variable importance.",
    "Statistical post-processing for shallow FNNs."
  ),
  `Fits FNNs` = c(
    "Yes",
    "Yes",
    "Yes",
    "Yes",
    "No",
    "No",
    "No",
    "No",
    "Via \\code{nn\\_fit()} convenience wrapper"
  ),
  `Regression-style summaries` = c(
    "Limited",
    "Limited",
    "No",
    "No",
    "No",
    "No",
    "No",
    "No",
    "Yes"
  ),
  `Covariate-level Wald summaries` = c(
    "No",
    "No",
    "No",
    "No",
    "No",
    "No",
    "No",
    "No",
    "Yes"
  ),
  `PCE plots with uncertainty` = c(
    "No",
    "No",
    "No",
    "No",
    "No",
    "No",
    "No",
    "No",
    "Yes"
  ),
  check.names = FALSE
)

knitr::kable(
  software_comparison,
  caption = "Comparison of \\pkg{interpretnn} with selected neural-network fitting and model-interpretability packages.",
  escape = FALSE
)


## ----interpretnn-call, echo = TRUE, eval = FALSE------------------------------
# interpretnn(object, ...)


## ----interpretnn-workflow, echo = TRUE, eval = FALSE--------------------------
# # 1. Fit a neural network
# nn <- nn_fit(
#   formula = charges ~ .,
#   data = insurance,
#   q = 2,
#   n_init = 10,
#   lambda = 0.01,
#   pkg = "nnet"
# )
# 
# # 2. Convert to an interpretnn object
# intnn <- interpretnn(nn)
# 
# # 3. Inspect the fitted model
# print(intnn)
# summary(intnn)
# aov(intnn)
# 
# # 4. Visualise the fitted model
# plot(intnn, which = c("age", "smoker"), conf_int = TRUE)
# plotnn(intnn)
# 
# # 5. Predict for new observations
# predict(intnn, newdata = insurance[1:5, ])


## ----interpretnn-nn-fit, echo = TRUE, eval = FALSE----------------------------
# library(interpretnn)
# 
# set.seed(1237019)
# 
# nn <- nn_fit(
#   formula = charges ~ .,
#   data = insurance,
#   q = 2,
#   n_init = 10,
#   lambda = 0.01,
#   pkg = "nnet"
# )


## ----interpretnn-create-object, echo = TRUE, eval = FALSE---------------------
# intnn <- interpretnn(object = nn)


## ----interpretnn-components-table, echo = FALSE, results = "asis"-------------
knitr::kable(
  data.frame(
    Component = c(
      "`weights`",
      "`loss_val`",
      "`n_inputs`",
      "`n_nodes`",
      "`n_layers`",
      "`n_param`",
      "`n`",
      "`loglike`",
      "`BIC`",
      "`eff`",
      "`wald`",
      "`wald_sp`",
      "`X`",
      "`y`",
      "`response`",
      "`lambda`"
    ),
    Description = c(
      "Vector of fitted neural-network parameters.",
      "Value of the relevant loss function.",
      "Number of input nodes.",
      "Number of hidden nodes in each hidden layer.",
      "Number of hidden layers.",
      "Number of model parameters.",
      "Number of observations in the training data.",
      "Value of the model log-likelihood.",
      "Bayesian information criterion for the fitted model.",
      "Point-estimate partial covariate effects and standard errors.",
      "Multiple-parameter Wald-type summaries for input nodes and covariates.",
      "Single-parameter Wald-type summaries for individual weights.",
      "Model matrix used by the fitted neural network.",
      "Response vector.",
      "Response type, such as continuous or binary.",
      "Ridge penalty used in fitting."
    )
  ),
  caption = "Main components of an object of class `interpretnn`.",
  escape = TRUE
)


## ----interpretnn-print, echo = TRUE, eval = FALSE-----------------------------
# print(intnn)


## ----interpretnn-summary, echo = TRUE, eval = FALSE---------------------------
# summary(intnn)


## ----interpretnn-summary-single, echo = TRUE, eval = FALSE--------------------
# summary(intnn, wald_single_par = TRUE)


## ----interpretnn-aov, echo = TRUE, eval = FALSE-------------------------------
# aov(intnn)


## ----interpretnn-plotnn, echo = TRUE, eval = FALSE----------------------------
# plotnn(intnn)


## ----interpretnn-plot, echo = TRUE, eval = FALSE------------------------------
# plot(intnn, which = c("age", "smoker"), conf_int = TRUE)


## ----interpretnn-plot-delta, echo = TRUE, eval = FALSE------------------------
# plot(
#   intnn,
#   which = "age",
#   conf_int = TRUE,
#   method = "delta_method"
# )


## ----interpretnn-plot-sim, echo = TRUE, eval = FALSE--------------------------
# plot(
#   intnn,
#   which = "age",
#   conf_int = TRUE,
#   method = "mlesim"
# )


## ----interpretnn-predict-training, echo = TRUE, eval = FALSE------------------
# predict(intnn)


## ----interpretnn-predict-newdata, echo = TRUE, eval = FALSE-------------------
# predict(intnn, newdata = insurance[1:5, ])


## ----example-data, echo = TRUE, eval = FALSE----------------------------------
# data("insurance", package = "interpretnn")
# 
# str(insurance)


## ----example-formula, echo = TRUE, eval = FALSE-------------------------------
# formula <- charges ~ age + sex + bmi + children + smoker + region


## ----example-fit, echo = TRUE, eval = FALSE-----------------------------------
# library(interpretnn)
# 
# set.seed(1237019)
# 
# nn <- nn_fit(
#   formula = charges ~ age + sex + bmi + children + smoker + region,
#   data = insurance,
#   q = 2,
#   n_init = 10,
#   lambda = 0.01,
#   pkg = "nnet"
# )


## ----example-create-interpretnn, echo = TRUE, eval = FALSE--------------------
# intnn <- interpretnn(nn)


## ----example-print, echo = TRUE, eval = FALSE---------------------------------
# print(intnn)


## ----example-summary, echo = TRUE, eval = FALSE-------------------------------
# summary(intnn)


## ----example-summary-single, echo = TRUE, eval = FALSE------------------------
# summary(intnn, wald_single_par = TRUE)


## ----example-aov, echo = TRUE, eval = FALSE-----------------------------------
# aov(intnn)


## ----example-plotnn, echo = TRUE, eval = FALSE, fig.cap = "Fitted neural-network architecture for the insurance data, annotated using Wald-type summaries."----
# plotnn(intnn)


## ----example-plotnn-alpha, echo = TRUE, eval = FALSE--------------------------
# plotnn(intnn, alpha = 0.01)


## ----example-plotnn-intercept, echo = TRUE, eval = FALSE----------------------
# plotnn(intnn, intercept = TRUE)


## ----example-pce-bmi, echo = TRUE, eval = FALSE, fig.cap = "Partial covariate-effect plot for body mass index in the insurance data."----
# plot(intnn, which = "bmi", conf_int = TRUE)


## ----example-pce-smoker, echo = TRUE, eval = FALSE, fig.cap = "Partial covariate-effect plot for smoking status in the insurance data."----
# plot(intnn, which = "smoker", conf_int = TRUE)


## ----example-pce-multiple, echo = TRUE, eval = FALSE, fig.cap = "Partial covariate-effect plots for selected covariates in the insurance data."----
# plot(
#   intnn,
#   which = c("age", "bmi", "children", "smoker"),
#   conf_int = TRUE
# )


## ----example-pce-delta, echo = TRUE, eval = FALSE-----------------------------
# plot(
#   intnn,
#   which = "age",
#   conf_int = TRUE,
#   method = "delta_method"
# )


## ----example-pce-sim, echo = TRUE, eval = FALSE-------------------------------
# plot(
#   intnn,
#   which = "age",
#   conf_int = TRUE,
#   method = "mlesim"
# )


## ----example-pce-interaction, echo = TRUE, eval = FALSE, fig.cap = "Partial covariate-effect plot for body mass index by smoking status."----
# plot(
#   intnn,
#   which = "bmi",
#   by = "smoker",
#   conf_int = TRUE
# )


## ----example-predict-training, echo = TRUE, eval = FALSE----------------------
# fitted_values <- predict(intnn)
# 
# head(fitted_values)


## ----example-predict-newdata, echo = TRUE, eval = FALSE-----------------------
# predict(intnn, newdata = insurance[1:5, ])


## ----interpretnn-methods-table, echo = FALSE, results = "asis"----------------
knitr::kable(
  data.frame(
    Function = c(
      "`nn_fit()`",
      "`interpretnn()`",
      "`print()`",
      "`summary()`",
      "`aov()`",
      "`plot()`",
      "`plotnn()`",
      "`predict()`"
    ),
    Purpose = c(
      "Fits a shallow FNN using a formula interface.",
      "Converts a fitted neural-network object into an object of class `interpretnn`.",
      "Prints a compact description of the fitted network and its architecture.",
      "Produces regression-style summaries, including PCE estimates and Wald-type summaries.",
      "Produces covariate-level Wald-type summaries, including grouped summaries for categorical covariates.",
      "Produces partial covariate-effect plots, with optional uncertainty intervals.",
      "Produces a neural-network architecture diagram annotated with Wald-type summaries.",
      "Returns fitted values or predictions for new observations."
    )
  ),
  caption = "Main user-facing functions and methods in `interpretnn`.",
  escape = TRUE
)

